### ISSUE TITLE
Not able to install from pypi

### ISSUE THREAD

**Issue by prakashpp** [goshippo/shippo-python-client#13]
Please check the following trace:

```
ubuntu@box165:~/shippo-python-client/shippo-1.2.1$ pip install shippo
Downloading/unpacking shippo
  Downloading shippo-1.2.1.tar.gz
  Running setup.py egg_info for package shippo
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-build-ubuntu/shippo/setup.py", line 5, in <module>
        from version import VERSION
    ImportError: No module named version
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-build-ubuntu/shippo/setup.py", line 5, in <module>

    from version import VERSION

ImportError: No module named version

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-ubuntu/shippo
Storing complete log in /home/ubuntu/.pip/pip.log
```

Can you confirm if this is happening on your end too? Happy to send a pull request ;)

**Comment by mnowik** [comment]
@prakashpp I am looking into it right now. I thought I fixed it on my previous PR.

**Comment by mnowik** [comment]
@prakashpp I installed `shippo-1.2.1` successfully on a new virtualenv. I also ran all the tests without error. Is it possible that your eggs are cached? Could you delete them in order to force a new download.
Let me know if you still encounter a problem after cleaning your eggs.

**Comment by prakashpp** [comment]
@mnowik ah! let me check that, may be my CI is caching eggs.

**Comment by prakashpp** [comment]
@mnowik I tried cleaning eggs but it doesnt help. I downloaded the latest release code from pypi, it clearly shows that the version file is inside shippo package and setup.py cannot access it.

Can you try this `https://pypi.python.org/packages/65/31/4de4bd2f6ce12cec0608fc4d873f61bcd5b829c79920d68f8d0d433ccdeb/shippo-1.2.1.tar.gz#md5=d447d2d139017e0564e937af4349f851`?

**Comment by prakashpp** [comment]
@mnowik sorry, got to know my pip was outdated. Thanks for the help.
