### ISSUE TITLE
setting Async=False does nothing for Transaction.create

### ISSUE THREAD

**Issue by daxaxelrod** [goshippo/shippo-python-client#53]
Im trying to create a transaction after I create a label. I need the shipping label as soon as I make the request.

I've set async (well i found and replaced all async with asynchronous but same concept) to False. I see in get_rates, there is a little if statement that will just continue to poll your api using cls.retrieve(blah).status in ("QUEUED", "WAITING").

any advice to ensure a deterministic outcome whether or not it went through after I create a transaction?

Thanks

**Comment by jfriedr** [comment]
@daxaxelrod I would recommend using webhooks (we sent a POST to your endpoint with a payload that contains the status of the created transactions):

transaction_created

Note that all your webhook needs to do is respond with a 200 -> webhook walkthrough [https://goshippo.com/docs/webhooks/](url)

You can create a webhook within the webapp:

![image](https://user-images.githubusercontent.com/61479880/157289666-06f4bd6e-1e16-4a45-bc36-cfd08a318101.png)

Or you can create a webhook via this SDK (or the API).  An example of this can be located here:

https://github.com/goshippo/shippo-python-client/blob/efec396c837e7c5cb3853d3ff60fd645104fe8e1/examples/tracking.py#L28
