### ISSUE TITLE
Module 'shippo' has no 'config' memberpylint(no-member)

### ISSUE THREAD

**Issue by mayank-budhiraja** [goshippo/shippo-python-client#58]
I installed shippo package and I was testing the example in readme but it doesn't work for me. It gives out an error `Module 'shippo' has no 'config' memberpylint(no-member)`

Please, help.

**Comment by hwangm** [comment]
Hi mayank, which version did you install? You have to specify installing version 2.0.0rc1 because it is currently not set as the default in pypi. Try reinstalling with `pip install shippo==2.0.0rc1` and retry the example as we moved the constants from `shippo` to `shippo.config` in this release.

**Comment by hwangm** [comment]
version 2.0.0 was released today. If you try again `pip install shippo` again it should download 2.0.0 and you should be good to go.

**Comment by mayank-budhiraja** [comment]
Now fixed. Thanks

> Hi mayank, which version did you install? You have to specify installing version 2.0.0rc1 because it is currently not set as the default in pypi. Try reinstalling with `pip install shippo==2.0.0rc1` and retry the example as we moved the constants from `shippo` to `shippo.config` in this release.

This worked fine. Thanks
