### ISSUE TITLE
Requests library upgrade 

### ISSUE THREAD

**Issue by TysonRV** [goshippo/shippo-python-client#64]
Hi all, 

is there any reason or incompatibility issue for not upgrading `requests` library's version? It would be great if the shippo client could allow it to work with its latest version (`2.24.0`). 

I can't imagine there is any breaking changes or issues coming from that!

**Comment by jfriedr** [comment]
There's not a specific reason from what I can tell.  From what I've found if there's a dependency issue people will just fork the repo and make the changes within setup.py change and then `pip install .` .

Is there a reason why you need the latest version?  Any context would bet great. 

Are you using other packages that require `2.24.0`?  

Are you using a specific platform that doesn't have that version available?

**Comment by TysonRV** [comment]
Well, we were considering of using a trustpilot wrapper: https://github.com/trustpilot/python-trustpilot

Yeah, maybe latest version was a bit too far! `2.22.0` would be enough in this case. Anyway, probably trustpilot guys can be also a bit more flexible with their `requests` setup, considering that's a well maintained and stable python package. 

Happy to fork it and make a PR out of it, if you think that's worth it. 

From what I can see, you guys are planning to ship a new release soon.
