### ISSUE TITLE
AttributeError: module 'shippo' has no attribute 'config'

### ISSUE THREAD

**Issue by cnr91** [goshippo/shippo-python-client#97]
I installed the shippo library. whenever i run your example code i get this error.

AttributeError: module 'shippo' has no attribute 'config'

<img width="215" alt="2023-03-13_140052" src="https://user-images.githubusercontent.com/75105673/224683309-a1cb9ff1-1d18-4664-a90a-b19cb5b2f566.png">

**Comment by cnr91** [comment]
Do not type shippo in the python filename. That's the cause of the problem.

**Comment by stealth-d** [comment]
running in python shell and getting the same error

**Comment by jfriedr** [comment]
@cnr91 @stealth-d could you try this sdk and let us know if you have any issues there:

https://github.com/goshippo/shippo-python-sdk

it's been pushed to pypi

https://pypi.org/project/shippo/3.0.0/
