### ISSUE TITLE
New pypi release needed -- is this still maintained?

### ISSUE THREAD

**Issue by dustinblanchard** [goshippo/shippo-python-client#99]
This repo badly needs a new release to pypl to fix the requests dependencies issue. Is anyone still maintaining it or should I find another approach?

**Comment by ulgens** [comment]
Same question here 🙂 I can help with updates and fixes, but it looks like the package is not maintained anymore.

**Comment by darkevilmac** [comment]
Seconding this, if shippo doesn't plan on maintaining their official clients then they need to at least make that clear considering it's a paid service.

**Comment by kerrermanisNL** [comment]
Any update on this?

**Comment by 9cb14c1ec0** [comment]
I needed features added, so I created a fork that I will be maintaining: https://github.com/9cb14c1ec0/shippo-python-client.  It is the shippo3 project on pypi

**Comment by shippo-lueders** [comment]
This client is not actively maintained and the project will soon be archived.  

A new codebase has been created https://github.com/goshippo/shippo-python-sdk which is generated from and will be kept up to date with the public OpenAPI Specification https://docs.goshippo.com/spec/shippoapi/public-api.yaml.  

The new SDK has been published to PyPI at version 3.0.0 and updates will be published as the spec evolves.
